name = "goko-whisper"
main = "src/index.ts"
compatibility_date = "2025-09-24"

[assets]
directory = "../frontend/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "goko-whispe-db"
database_id = "d415717a-3069-4444-8b98-a675a32bb50c"
migrations_dir = "migrations"

[[previews.d1_databases]]
binding = "DB"
database_name = "goko-whisper-db-preview"
database_id = "c16c6af4-82d4-4f16-bb6e-42cd476cf08f"